sudo: false

language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - memcached
  - mongodb
  - redis-server

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"
    - TESTS_ZEND_CACHE_APC_ENABLED=true
    - TESTS_ZEND_CACHE_APCU_ENABLED=true
    - TESTS_ZEND_CACHE_FILESYSTEM_DIR=/dev/shm
    - TESTS_ZEND_CACHE_MEMCACHED_ENABLED=true
    - TESTS_ZEND_CACHE_MEMCACHED_HOST="127.0.0.1"
    - TESTS_ZEND_CACHE_MEMCACHED_PORT=11211
    - TESTS_ZEND_CACHE_MEMCACHE_ENABLED=true
    - TESTS_ZEND_CACHE_MEMCACHE_HOST=$TESTS_ZEND_CACHE_MEMCACHED_HOST
    - TESTS_ZEND_CACHE_MEMCACHE_PORT=$TESTS_ZEND_CACHE_MEMCACHED_PORT
    - TESTS_ZEND_CACHE_MONGODB_ENABLED=true
    - TESTS_ZEND_CACHE_REDIS_ENABLED=true
    - TESTS_ZEND_CACHE_REDIS_HOST="127.0.0.1"
    - TESTS_ZEND_CACHE_REDIS_PORT=6379
    - TESTS_ZEND_CACHE_REDIS_PASSWORD=""
    - TESTS_ZEND_CACHE_REDIS_DATABASE=0
    - TESTS_ZEND_CACHE_XCACHE_ENABLED=true
    - TESTS_ZEND_CACHE_XCACHE_ADMIN_AUTH=true
    - TESTS_ZEND_CACHE_XCACHE_ADMIN_USER=travis
    - TESTS_ZEND_CACHE_XCACHE_ADMIN_PASS=test

matrix:
  include:
    - php: 5.6
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-4.0.8"
    - php: 5.6
      env:
        - DEPS=locked
        - LEGACY_DEPS="phpunit/phpunit"
        - APCU_PECL_VERSION="apcu-4.0.10"
    - php: 5.6
      env:
        - DEPS=latest
        - APCU_PECL_VERSION="apcu-4.0.11"
    - php: 7
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-5.1.2"
        - APCU_BC_PECL_VERSION="apcu_bc-1.0.0"
    - php: 7
      env:
        - DEPS=locked
        - LEGACY_DEPS="phpunit/phpunit"
        - APCU_PECL_VERSION="apcu-5.1.3"
        - APCU_BC_PECL_VERSION="apcu_bc-1.0.2"
    - php: 7
      env:
        - DEPS=latest
        - APCU_PECL_VERSION="apcu"
        - APCU_BC_PECL_VERSION="apcu_bc-1.0.3"
    - php: 7.1
      env:
        - DEPS=lowest
        - APCU_PECL_VERSION="apcu-5.1.2"
        - APCU_BC_PECL_VERSION="apcu_bc-1.0.0"
    - php: 7.1
      env:
        - DEPS=locked
        - CS_CHECK=true
        - TEST_COVERAGE=true
        - APCU_PECL_VERSION="apcu-5.1.3"
        - APCU_BC_PECL_VERSION="apcu_bc-1.0.2"
    - php: 7.1
      env:
        - DEPS=latest
        - APCU_PECL_VERSION="apcu"
        - APCU_BC_PECL_VERSION="apcu_bc-1.0.3"
    - php: 7.2
      env:
        - DEPS=lowest
        - TESTS_ZEND_CACHE_APCU_ENABLED=false
    - php: 7.2
      env:
        - DEPS=locked
        - TESTS_ZEND_CACHE_APCU_ENABLED=false
    - php: 7.2
      env:
        - DEPS=latest
        - TESTS_ZEND_CACHE_APCU_ENABLED=false

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi

install:
  # prevent PECL from enabling the extension by default, see https://pear.php.net/bugs/bug.php?id=21007
  - if [[ $APCU_PECL_VERSION != '' ]]; then
        echo "yes\nno\n" | pecl install $APCU_PECL_VERSION
        && sed -i 's/extension="apcu.so"//' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ;
    fi

  - if [[ $APCU_BC_PECL_VERSION != '' ]]; then
        pecl install $APCU_BC_PECL_VERSION
        && sed -i 's/extension="apc.so"//' ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini ;
    fi

  - if [[ $TESTS_ZEND_CACHE_XCACHE_ENABLED == 'true' ]]; then
        git clone https://github.com/lighttpd/xcache.git
        && (
            cd xcache
            && git checkout $(git rev-list --tags --max-count=1)
            && phpize && ./configure --enable-xcache && make install
        );
    fi

  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - stty cols 120 && composer show

before_script:
  - if [[ $APCU_PECL_VERSION != '' && $APCU_BC_PECL_VERSION == '' ]]; then
        phpenv config-add .ci/apcu.ini ;
    elif [[ $APCU_BC_PECL_VERSION != '' ]]; then
        phpenv config-add .ci/apcu_bc.ini ;
    fi ;
    if [[ $TESTS_ZEND_CACHE_REDIS_ENABLED == 'true' ]]; then
        phpenv config-add .ci/redis.ini ;
    fi ;
    if [[ $TESTS_ZEND_CACHE_MEMCACHE_ENABLED == 'true' ]]; then
        phpenv config-add .ci/memcache.ini ;
    fi ;
    if [[ $TESTS_ZEND_CACHE_MEMCACHED_ENABLED == 'true' ]]; then
        phpenv config-add .ci/memcached.ini ;
    fi ;
    if [[ $TESTS_ZEND_CACHE_MONGODB_ENABLED == 'true' ]]; then
        phpenv config-add .ci/mongo.ini ;
    fi ;
    if [[ $TESTS_ZEND_CACHE_XCACHE_ENABLED == 'true' ]]; then
        phpenv config-add .ci/xcache.ini ;
    fi ;

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer run-script test-coverage --timeout=400 -- --verbose ; else composer run-script test --timeout=300 -- --verbose ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
