language: php

cache:
  directories:
    - $HOME/.composer/cache

services:
  - mongodb
  - redis-server

env:
  global:
    - COMPOSER_ARGS="--no-interaction"
    - COVERAGE_DEPS="php-coveralls/php-coveralls"
    - TESTS_LAMINAS_CACHE_FILESYSTEM_DIR=/dev/shm
    - TESTS_LAMINAS_CACHE_MONGODB_ENABLED=true
    - TESTS_LAMINAS_CACHE_REDIS_ENABLED=true
    - TESTS_LAMINAS_CACHE_REDIS_HOST="127.0.0.1"
    - TESTS_LAMINAS_CACHE_REDIS_PORT=6379
    - TESTS_LAMINAS_CACHE_REDIS_PASSWORD=""
    - TESTS_LAMINAS_CACHE_REDIS_DATABASE=0
    - TESTS_LAMINAS_CACHE_XCACHE_ENABLED=false # Supported only on PHP 5.6
    - TESTS_LAMINAS_CACHE_XCACHE_ADMIN_AUTH=true
    - TESTS_LAMINAS_CACHE_XCACHE_ADMIN_USER=travis
    - TESTS_LAMINAS_CACHE_XCACHE_ADMIN_PASS=test
    - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=false

matrix:
  fast_finish: true
  include:
    - php: 5.6
      env:
        - DEPS=lowest
        - REDIS_PECL_VERSION="redis-2.2.3"
        - TESTS_LAMINAS_CACHE_XCACHE_ENABLED=true
    - php: 5.6
      env:
        - DEPS=latest
        - REDIS_PECL_VERSION="redis-4.3.0"
        - TESTS_LAMINAS_CACHE_XCACHE_ENABLED=true
    - php: 7
      env:
        - DEPS=lowest
        - REDIS_PECL_VERSION="redis-4.0.0"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true
    - php: 7
      env:
        - DEPS=latest
        - REDIS_PECL_VERSION="redis"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true
    - php: 7.1
      env:
        - DEPS=lowest
        - REDIS_PECL_VERSION="redis-4.0.0"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true
    - php: 7.1
      env:
        - DEPS=latest
        - CS_CHECK=true
        - BENCHMARKS=true
        - TEST_COVERAGE=true
        - REDIS_PECL_VERSION="redis"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true
    - php: 7.2
      env:
        - DEPS=lowest
        - REDIS_PECL_VERSION="redis-4.0.0"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true
    - php: 7.2
      env:
        - DEPS=latest
        - REDIS_PECL_VERSION="redis"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true
    - php: 7.3
      env:
        - DEPS=lowest
        - REDIS_PECL_VERSION="redis-4.0.0"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true
    - php: 7.3
      env:
        - DEPS=latest
        - REDIS_PECL_VERSION="redis"
        - TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL=true

before_install:
  - if [[ $TEST_COVERAGE != 'true' ]]; then phpenv config-rm xdebug.ini || return 0 ; fi
  - pecl channel-update pecl.php.net

install:
  - if [[ $TESTS_LAMINAS_CACHE_XCACHE_ENABLED == 'true' ]]; then
        git clone https://github.com/lighttpd/xcache.git
        && (
            cd xcache
            && git checkout $(git rev-list --tags --max-count=1)
            && phpize && ./configure --enable-xcache && make install
        );
    fi ;

  - if [[ $TESTS_LAMINAS_CACHE_REDIS_ENABLED == 'true' ]]; then
        echo "no" | pecl install -f $REDIS_PECL_VERSION ;
    fi ;

  - if [[ $TESTS_LAMINAS_CACHE_MONGODB_ENABLED == 'true' && $TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL != 'true' ]]; then
        phpenv config-add .ci/mongo.ini ;
    fi ;

  - if [[ $TESTS_LAMINAS_CACHE_XCACHE_ENABLED == 'true' ]]; then
        phpenv config-add .ci/xcache.ini ;
    fi ;

  - travis_retry composer install $COMPOSER_ARGS --ignore-platform-reqs
  - if [[ $LEGACY_DEPS != '' ]]; then travis_retry composer update $COMPOSER_ARGS --with-dependencies $LEGACY_DEPS ; fi
  - if [[ $DEPS == 'latest' ]]; then travis_retry composer update $COMPOSER_ARGS ; fi
  - if [[ $DEPS == 'lowest' ]]; then travis_retry composer update --prefer-lowest --prefer-stable $COMPOSER_ARGS ; fi
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry composer require --dev $COMPOSER_ARGS $COVERAGE_DEPS ; fi
  - if [[ $TESTS_LAMINAS_CACHE_MONGODB_USE_POLYFILL == 'true' ]]; then travis_retry composer require --dev --no-update $COMPOSER_ARGS mongofill/mongofill:dev-master ; fi
  - stty cols 120 && composer show
  - pecl list
  - php -m

script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then composer run-script test-coverage -- --verbose ; else composer run-script test -- --verbose ; fi
  - if [[ $BENCHMARKS == 'true' ]]; then vendor/bin/phpbench run --revs=2 --iterations=2 --report=aggregate ; fi
  - if [[ $CS_CHECK == 'true' ]]; then composer cs-check ; fi

after_script:
  - if [[ $TEST_COVERAGE == 'true' ]]; then travis_retry vendor/bin/php-coveralls -v ; fi

notifications:
  email: false
